IF (OBJECT_ID('dbo.FI_SP_IncBeneficiario') IS NOT NULL) DROP PROCEDURE dbo.FI_SP_IncBeneficiario
GO
CREATE PROC FI_SP_IncBeneficiario
    @NOME          VARCHAR (50) ,
    @CPF           VARCHAR (15),
	@IDCLIENTE     BIGINT
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END