IF (OBJECT_ID('dbo.FI_SP_ConsBeneficiarioCliente') IS NOT NULL) DROP PROCEDURE dbo.FI_SP_ConsBeneficiarioCliente
GO
CREATE PROC FI_SP_ConsBeneficiarioCliente
	@ID BIGINT
AS
BEGIN
	--IF(ISNULL(@ID,0) = 0)
	--	SELECT ID, IDCLIENTE, NOME, CPF FROM BENEFICIARIOS WITH(NOLOCK)
	--ELSE
		SELECT  ID, IDCLIENTE, NOME, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @ID
END