IF (OBJECT_ID('dbo.FI_SP_VerificaBeneficiario') IS NOT NULL) DROP PROCEDURE dbo.FI_SP_VerificaBeneficiario
GO
CREATE PROC FI_SP_VerificaBeneficiario
	@CPF CHAR(11),
	@IDCLIENTE bigint,
	@ID bigint
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT ID, IDCLIENTE, NOME, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF AND IDCLIENTE=@IDCLIENTE
	ELSE
		SELECT  ID, IDCLIENTE, NOME, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF AND IDCLIENTE=@IDCLIENTE and Id <> @ID
END


